### ISSUE TITLE
Fixing the output from json format to more readble manner.

### ISSUE THREAD

**Issue by Sreenivasan2002** [Sreenivasan2002/TrackScore---ATS-Resume-score-checker#1]
After uploading the job description and Resume when we click the submit button, the response is in json format. 
The issue can be checked it on this website by uploading JD and resume: https://trackerscore.streamlit.app/

![issue](https://github.com/user-attachments/assets/b409bd39-8a82-4164-8236-34f2165b4286)

**Comment by amritrout** [comment]
I’d like to take this issue. Please assign it to me so I can start working on it. Thank you.
